### ISSUE TITLE
Callers are not displayed.

### ISSUE THREAD

**Issue by chordtoll** [devdri/awake#1]
In database.py, on line 79, addr is overwritten by the address of the last memory location referenced, causing callers to return an incorrect or empty set. This can be fixed by changing lines 79-83 to:

```
79    for address, reftype in c.fetchall():
80        if reftype == 'read':
81            self.memreads.add(address)
82        else:
83            self.memwrites.add(address)
```

**Comment by devdri** [comment]
Thanks, pushed the patch with your name. Apparently I was too careless with latest refactorings. Btw. a commit I just pushed changes one column type (for automatic address object deserialize), which will trigger assert in one place on old db files.
